FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish Configuration.TestHarness/ConsulRx.Configuration.TestHarness.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
CMD ["dotnet", "ConsulRx.Configuration.TestHarness.dll"]
