services:
  consul:
    image: hashicorp/consul
    ports:
    - '8500:8500'
    command: ["agent", "-dev", "-client", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 2s
      timeout: 3s
      retries: 10
  seeder:
    build:
      context: .
      dockerfile: Dockerfile-ConsulSeeder
    environment:
      CONSUL_HTTP_ADDR: "consul:8500"
    depends_on:
      consul:
        condition: service_healthy
  web:
    build:
      context: ..
      dockerfile: Configuration.TestHarness/Dockerfile-TestHarness
    ports:
    - '8080:8080'
    environment:
      CONSUL_HTTP_ADDR: "consul:8500"
    depends_on:
      seeder:
        condition: service_completed_successfully
  