image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
- build
- publish

variables:
  Configuration: Release
  NoSourceLink: 'true'
  
build:
  stage: build
  script:
  - ./build.sh
  - dotnet publish -r linux-x64 /p:PublishSingleFile=true Templating.CommandLine/ConsulRx.Templating.CommandLine.csproj
  artifacts:
    name: ConsulRx-$CI_PIPELINE_ID
    when: on_success
    paths: 
    - ConsulRx/bin/$Configuration/*.nupkg
    - Configuration/bin/$Configuration/*.nupkg
    - Templating.CommandLine/bin/$Configuration/net6.0/linux-x64/publish/**

publish ConsulRx to nuget.org:
  stage: publish
  only:
  - master
  script:
  - dotnet nuget push $(ls ConsulRx/bin/$Configuration/*.nupkg) -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json  
  environment:
    name: nuget.org
    url: https://nuget.org/packages/ConsulRx/
  when: manual

publish Configuration to nuget.org:
  stage: publish
  only:
  - master
  script:
  - dotnet nuget push $(ls Configuration/bin/$Configuration/*.nupkg) -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json  
  environment:
    name: nuget.org
    url: https://nuget.org/packages/ConsulRx.Configuration/
  when: manual  